# magpi/mgt.py
import logging
import os
import numpy as np
import geopandas as gpd
from shapely.geometry import box
from .objects import Result

logger = logging.getLogger("MagPI_Management")

def BuildPyramidsAndStats(in_dataset, build_pyramids=True, calculate_stats=True):
    """
    MagPI Translation of arcpy.management.BuildPyramidsAndStats.
    Bakes fast-rendering overviews and min/max/mean statistics directly into the GeoTIFF header.
    """
    if hasattr(in_dataset, 'name'): raster_path = in_dataset.name
    elif hasattr(in_dataset, 'output'): raster_path = in_dataset.output
    else: raster_path = str(in_dataset)

    logger.info(f"Executing Open-Source Build Pyramids/Stats on: {os.path.basename(raster_path)}")
    try:
        import rasterio
        from rasterio.enums import Resampling
        
        with rasterio.open(raster_path, 'r+') as src:
            if calculate_stats:
                logger.info(f"Calculating array statistics for {src.count} bands...")
                for i in range(1, src.count + 1):
                    band_data = src.read(i)
                    valid_data = band_data[band_data != src.nodata] if src.nodata is not None else band_data
                    
                    if valid_data.size > 0:
                        src.update_tags(i, 
                            STATISTICS_MINIMUM=float(np.min(valid_data)),
                            STATISTICS_MAXIMUM=float(np.max(valid_data)),
                            STATISTICS_MEAN=float(np.mean(valid_data)),
                            STATISTICS_STDDEV=float(np.std(valid_data))
                        )
            
            if build_pyramids:
                logger.info("Building internal pyramid overviews...")
                factors = [2, 4, 8, 16]
                src.build_overviews(factors, Resampling.average)
                src.update_tags(ns='rio_overview', resampling='average')
                
        logger.info("SUCCESS: Statistics and Overviews baked successfully.")
        return Result(raster_path)
    except Exception as e:
        logger.error(f"Failed to build pyramids/stats: {e}")
        return Result(None, status=3)

def Clip(in_raster, clip_extent, out_raster):
    """
    MagPI Translation of arcpy.management.Clip.
    Surgically extracts a spatial subset of a larger raster.
    """
    if hasattr(in_raster, 'name'): raster_path = in_raster.name
    else: raster_path = str(in_raster)

    logger.info(f"Initiating Raster Clip Operation on: {os.path.basename(raster_path)}")
    try:
        import rasterio
        from rasterio.windows import from_bounds
        
        if hasattr(clip_extent, 'XMin'): min_lon, min_lat, max_lon, max_lat = clip_extent.XMin, clip_extent.YMin, clip_extent.XMax, clip_extent.YMax
        else: min_lon, min_lat, max_lon, max_lat = map(float, str(clip_extent).split())
        
        with rasterio.open(raster_path) as src:
            # Transform the bounding box if the CRS doesn't match
            if src.crs.to_epsg() != 4326:
                from rasterio.warp import transform_bounds
                min_lon, min_lat, max_lon, max_lat = transform_bounds('EPSG:4326', src.crs, min_lon, min_lat, max_lon, max_lat)

            window = from_bounds(min_lon, min_lat, max_lon, max_lat, src.transform).round_offsets().round_lengths()
            
            out_meta = src.meta.copy()
            out_meta.update({
                "driver": "GTiff",
                "height": window.height,
                "width": window.width,
                "transform": src.window_transform(window)
            })
            
            with rasterio.open(out_raster, "w", **out_meta) as dest:
                dest.write(src.read(window=window))
                dest.update_tags(COPYRIGHT="Generated by MagPI - NexaVision.tech")
                
        logger.info(f"SUCCESS: Clipped raster saved to: {out_raster}")
        return Result(out_raster)
    except Exception as e:
        logger.error(f"Clip failed: {e}")
        return Result(None, status=3)

def ProjectRaster(in_raster, out_raster, out_crs, resampling_type="NEAREST"):
    """
    MagPI Translation of arcpy.management.ProjectRaster.
    Permanently warps a raster file to a new Coordinate Reference System on disk.
    """
    if hasattr(in_raster, 'name'): raster_path = in_raster.name
    else: raster_path = str(in_raster)

    logger.info(f"Initiating Geospatial Projection: {os.path.basename(raster_path)} -> {out_crs}")
    try:
        import rasterio
        from rasterio.warp import calculate_default_transform, reproject, Resampling
        
        resampling_enum = getattr(Resampling, resampling_type.lower(), Resampling.nearest)
        dst_crs = out_crs if ':' in out_crs else f"EPSG:{out_crs}"
        
        with rasterio.open(raster_path) as src:
            transform, width, height = calculate_default_transform(src.crs, dst_crs, src.width, src.height, *src.bounds)
            kwargs = src.meta.copy()
            kwargs.update({'crs': dst_crs, 'transform': transform, 'width': width, 'height': height})
            
            with rasterio.open(out_raster, 'w', **kwargs) as dst:
                for i in range(1, src.count + 1):
                    reproject(
                        source=rasterio.band(src, i),
                        destination=rasterio.band(dst, i),
                        src_transform=src.transform,
                        src_crs=src.crs,
                        dst_transform=transform,
                        dst_crs=dst_crs,
                        resampling=resampling_enum
                    )
                dst.update_tags(COPYRIGHT="Generated by MagPI - NexaVision.tech")
                
        logger.info(f"SUCCESS: Projected raster saved to: {out_raster}")
        return Result(out_raster)
    except Exception as e:
        logger.error(f"Projection failed: {e}")
        return Result(None, status=3)

def CreateFishnet(out_feature_class, extent, cell_width=2560, cell_height=2560):
    """
    MagPI Translation of arcpy.management.CreateFishnet.
    Generates a Shapefile/GeoJSON grid of polygons across a massive extent.
    Crucial for batching Deep Learning jobs at a national scale.
    """
    logger.info(f"Forging Spatial Fishnet Grid ({cell_width}m x {cell_height}m cells)...")
    try:
        if hasattr(extent, 'XMin'): min_lon, min_lat, max_lon, max_lat = extent.XMin, extent.YMin, extent.XMax, extent.YMax
        else: min_lon, min_lat, max_lon, max_lat = map(float, str(extent).split())
        
        # We need a metric projection to accurately draw meter-based cells
        from .env import env
        crs = f"EPSG:{env.outputCoordinateSystem}" if env.outputCoordinateSystem else "EPSG:3857"
        
        # Convert bounding box to metric space
        bounds_gdf = gpd.GeoDataFrame({'geometry': [box(min_lon, min_lat, max_lon, max_lat)]}, crs="EPSG:4326")
        metric_bounds = bounds_gdf.to_crs(crs).total_bounds
        m_xmin, m_ymin, m_xmax, m_ymax = metric_bounds
        
        # Generate Grid Coordinates
        x_coords = np.arange(m_xmin, m_xmax, cell_width)
        y_coords = np.arange(m_ymin, m_ymax, cell_height)
        
        polygons = []
        for x in x_coords:
            for y in y_coords:
                polygons.append(box(x, y, x + cell_width, y + cell_height))
                
        grid = gpd.GeoDataFrame({'geometry': polygons, 'Grid_ID': range(1, len(polygons)+1)}, crs=crs)
        grid.to_file(out_feature_class)
        
        logger.info(f"SUCCESS: Fishnet of {len(polygons)} tiles saved to: {out_feature_class}")
        return Result(out_feature_class)
    except Exception as e:
        logger.error(f"Fishnet generation failed: {e}")
        return Result(None, status=3)