import rasterio
from rasterio.windows import Window
import torch
import numpy as np
import logging
from torchvision.models.segmentation import fcn_resnet50
from torchvision.transforms import functional as F

logger = logging.getLogger("MagPI_GeoAI")

def ClassifyPixelsUsingDeepLearning(in_raster, out_raster, in_model_definition, padding=0, batch_size=4, processing_mode="Local"):
    """
    Executes a pre-trained PyTorch semantic segmentation model across a massive raster.
    Includes Modularity for Cluster (Airflow) vs Local execution.
    """
    if hasattr(in_raster, 'name'): raster_path = in_raster.name
    elif hasattr(in_raster, 'output'): raster_path = in_raster.output
    else: raster_path = str(in_raster)

    logger.info(f"Initiating Deep Learning Inference Engine ({processing_mode} Mode)...")
    logger.info(f"Target Raster: {raster_path}")
    
    try:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        logger.info(f"Inference Device Locked: {device.type.upper()}")
        
        # We will use a pre-trained FCN ResNet-50 as our baseline proxy for Gaian Mind CNNs
        logger.info("Loading PyTorch fcn_resnet50 Architecture (COCO Pre-trained)...")
        model = fcn_resnet50(pretrained=True)
        model = model.to(device)
        model.eval()

        with rasterio.open(raster_path) as src:
            out_meta = src.meta.copy()
            out_meta.update({
                "driver": "GTiff",
                "count": 1,
                "dtype": "uint8",
                "nodata": 255
            })
            
            logger.info("Scanning feature matrices through Neural Network...")
            with rasterio.open(out_raster, "w", **out_meta) as dest:
                tile_size = 512
                for y in range(0, src.height, tile_size):
                    for x in range(0, src.width, tile_size):
                        actual_width = min(tile_size, src.width - x)
                        actual_height = min(tile_size, src.height - y)
                        window = Window(x, y, actual_width, actual_height)
                        
                        # Read the RGB/NIR bands (Assuming first 3 bands map to RGB for standard models)
                        img_chunk = src.read((1, 2, 3), window=window)
                        
                        # Normalize to 0-1 for PyTorch and add batch dimension
                        tensor_chunk = torch.from_numpy(img_chunk).float() / 255.0
                        
                        # Pre-trained vision models expect 3 channels
                        if tensor_chunk.shape[0] != 3:
                            # Fallback if raster has 1 band or something weird
                            tensor_chunk = tensor_chunk.expand(3, -1, -1)
                        
                        tensor_chunk = tensor_chunk.unsqueeze(0).to(device)
                        
                        with torch.no_grad():
                            output = model(tensor_chunk)['out'][0]
                            # Output shape is [21, H, W] for COCO. Get the argmax class.
                            predicted_mask = output.argmax(0).byte().cpu().numpy()
                            
                        dest.write(predicted_mask, 1, window=window)
                        
                dest.update_tags(COPYRIGHT="Generated by MagPI - NexaVision.tech", SOFTWARE="MagPI GeoAI Engine")

        logger.info(f"SUCCESS: AI Inference complete. Classified Raster saved to: {out_raster}")
        from .objects import Result
        return Result(out_raster)

    except ImportError as e:
        logger.error(f"Failed to import PyTorch dependency: {str(e)}. Run: conda install pytorch torchvision -c pytorch")
        from .objects import Result
        return Result(None, status=3)
    except Exception as e:
        logger.error(f"Inference failed: {e}")
        from .objects import Result
        return Result(None, status=3)
