export const generateAirflowDAG = (nodes, connections, crs, globalEnv) => {
    let script = `# Generated by MagPI Visual Pipeline for Apache Airflow\n`;
    script += `import os\n`;
    script += `from datetime import datetime\n`;
    script += `from airflow.decorators import dag, task\n`;
    script += `import magpi as arcpy\n\n`;
    
    script += `# --- Global Environment ---\n`;
    if (globalEnv) {
        script += `WORKSPACE_DIR = "${globalEnv.workspace_dir}"\n`;
        script += `SCRATCH_DIR = "${globalEnv.scratch_dir}"\n`;
        script += `OUTPUT_DIR = "${globalEnv.output_dir}"\n`;
        script += `os.environ["MAGPI_WORKSPACE"] = WORKSPACE_DIR\n`;
        script += `os.environ["MAGPI_SCRATCH"] = SCRATCH_DIR\n`;
        script += `os.environ["MAGPI_OUTPUT"] = OUTPUT_DIR\n`;
    }
    const crsValue = crs.includes(':') ? crs.split(':')[1] : `"${crs}"`;
    script += `CRS = ${crsValue}\n\n`;
    
    script += `@dag(start_date=datetime(2026, 1, 1), schedule_interval='@daily', catchup=False, tags=['magpi', 'geospatial'])\n`;
    script += `def magpi_spatial_pipeline():\n\n`;

    // Map tool ids to python functions
    const toolToFunc = {
        'wfs_sentinel2': 'arcpy.wfs.PullSentinel2',
        'wfs_elevation': 'arcpy.wfs.PullUSGSElevation',
        'core_extent': 'arcpy.Extent',
        'load_raster': 'arcpy.Raster',
        'ia_ndvi': 'arcpy.ia.NDVI',
        'mgt_clip': 'arcpy.management.Clip',
        'mgt_buffer': 'arcpy.analysis.Buffer'
    };

    // Topological Sort
    const adjList = {};
    const inDegree = {};
    nodes.forEach(n => { adjList[n.id] = []; inDegree[n.id] = 0; });
    connections.forEach(c => {
        if (adjList[c.from]) {
            adjList[c.from].push(c.to);
            if (inDegree[c.to] !== undefined) inDegree[c.to]++;
        }
    });

    const queue = [];
    Object.keys(inDegree).forEach(id => { if (inDegree[id] === 0) queue.push(id); });
    queue.sort((a, b) => nodes.find(n => n.id === a).x - nodes.find(n => n.id === b).x);

    const sortedNodeIds = [];
    while (queue.length > 0) {
        const curr = queue.shift();
        sortedNodeIds.push(curr);
        let neighbors = adjList[curr];
        neighbors.forEach(neighbor => {
            inDegree[neighbor]--;
            if (inDegree[neighbor] === 0) queue.push(neighbor);
        });
    }

    const sortedNodes = sortedNodeIds.map(id => nodes.find(n => n.id === id)).filter(n => n !== undefined);
    
    const varMap = {};
    sortedNodes.forEach((n, idx) => { 
        varMap[n.id] = `${n.toolId.split('_').pop()}_task_${idx+1}`; 
    });

    // Write Tasks
    sortedNodes.forEach((n) => {
        const outVar = varMap[n.id];
        script += `    @task(task_id='${outVar}')\n`;
        
        // Find inputs
        const incomingCxs = connections.filter(c => c.to === n.id);
        const inputArgs = incomingCxs.map(c => varMap[c.from]).join(', ');
        
        script += `    def ${outVar}(${inputArgs ? '**kwargs' : ''}):\n`;
        
        // Extract kwargs dynamically if dependencies exist
        if (inputArgs) {
            incomingCxs.forEach(c => {
                script += `        ${varMap[c.from]} = kwargs.get('${varMap[c.from]}')\n`;
            });
        }

        const p = {};
        for (const [key, val] of Object.entries(n.params || {})) {
            p[key] = (val && typeof val === 'object' && val.type === 'select') ? val.value : val;
        }

        let funcCall = `        # TODO: Implement ${n.toolId}\n        return None\n`;
        const primaryInVar = incomingCxs.length > 0 ? varMap[incomingCxs[0].from] : 'None';

        if (n.toolId === 'core_extent') {
            funcCall = `        extent = arcpy.Extent(${p.xmin}, ${p.ymin}, ${p.xmax}, ${p.ymax})\n        return extent.to_json()`;
        }
        else if (n.toolId === 'core_date_variable') {
            funcCall = `        # Airflow injects {{ ds }} (Execution Date) into kwargs dynamically\n        # Fallback to visual canvas date if run manually outside Airflow scheduler\n        return kwargs.get('ds', "${p.date}")`;
        }
        else if (n.toolId === 'wfs_sentinel2') {
            funcCall = `        out_path = os.path.join(SCRATCH_DIR, "s2_cloud_extract_${n.id.split('_')[1]}.tif")\n        result = arcpy.wfs.PullSentinel2(${primaryInVar}, out_path, max_cloud_cover=${p.max_cloud_cover}, date_range="${p.start_date}/${p.end_date}")\n        return result.path`;
        }
        else if (n.toolId === 'ia_ndvi') {
            funcCall = `        result = arcpy.ia.NDVI(${primaryInVar}, nir_band_id=${p.nir_band}, red_band_id=${p.red_band})\n        return result.path`;
        }
        else if (n.toolId === 'mgt_clip') {
            funcCall = `        out_path = os.path.join(OUTPUT_DIR, "aoi_clip_${n.id.split('_')[1]}.tif")\n        result = arcpy.management.Clip(${primaryInVar}, ${incomingCxs.length > 1 ? varMap[incomingCxs[1].from] : 'extent'}, out_path)\n        return result.path`;
        }
        else if (n.toolId === 'community_structural_damage_volume') {
            let preDsmVar = 'None', postDsmVar = 'None', preOptVar = 'None', footVar = 'None';
            incomingCxs.forEach(c => {
                if (c.targetHandle === 'pre_dsm') preDsmVar = `kwargs.get('${varMap[c.from]}')`;
                else if (c.targetHandle === 'post_dsm') postDsmVar = `kwargs.get('${varMap[c.from]}')`;
                else if (c.targetHandle === 'pre_optical') preOptVar = `kwargs.get('${varMap[c.from]}')`;
                else if (c.targetHandle === 'footprints') footVar = `kwargs.get('${varMap[c.from]}')`;
            });
            
            funcCall = `        import sys\n        sys.path.append(os.path.join(WORKSPACE_DIR, "community_nodes"))\n        import bda_volume\n        from magpi.engine.nodes.registry import NODE_REGISTRY\n\n`;
            funcCall += `        damage_node = NODE_REGISTRY["community_structural_damage_volume"]()\n`;
            funcCall += `        damage_node.inputs = {"in_pre": ${preDsmVar}, "in_pre_optical": ${preOptVar}, "in_post": ${postDsmVar}, "in_vector": ${footVar}}\n`;
            funcCall += `        damage_node.params = {"collapse_threshold_meters": ${p.collapse_threshold_m || -2.5}, "solar_elevation_deg": ${p.solar_elevation_deg || 45.0}}\n`;
            funcCall += `        damage_node.execute()\n`;
            funcCall += `        return damage_node.output.get("classified_vector")`;
        }
        else {
            const genericFunc = toolToFunc[n.toolId] || `arcpy.${n.toolId}`;
            funcCall = `        print("Executing ${n.name}")\n        return ${genericFunc}(${primaryInVar})\n`;
        }

        script += `${funcCall}\n\n`;
    });

    script += `    # --- DAG Dependencies ---\n`;
    
    // Wire the execution graph
    sortedNodes.forEach(n => {
        const outVar = varMap[n.id];
        const incomingCxs = connections.filter(c => c.to === n.id);
        
        let callParams = [];
        incomingCxs.forEach(c => {
            callParams.push(`${varMap[c.from]}=${varMap[c.from]}_res`);
        });
        
        script += `    ${outVar}_res = ${outVar}(${callParams.join(', ')})\n`;
    });

    script += `\nmagpi_dag = magpi_spatial_pipeline()\n`;

    return script;
};
