export const generatePythonScript = (nodes, connections, crs, processingScope) => {
    let script = `# Generated by MagPI Canvas (v0.1.47 Alpha)\n`;
    script += `import magpi as arcpy\n`;
    script += `import os\n\n`;
    
    script += `# --- Global Environment ---\n`;
    script += `arcpy.env.workspace = "./tmp_wksp"\n`;
    
    const crsValue = crs.includes(':') ? crs.split(':')[1] : `"${crs}"`;
    script += `arcpy.env.outputCoordinateSystem = ${crsValue}\n`;
    script += `arcpy.env.overwriteOutput = True\n\n`;
    
    script += `arcpy.AddMessage("Initiating MagPI Visual Model execution...")\n\n`;
    
    // --- MAGPI TOPOLOGICAL SORT ---
    const adjList = {};
    const inDegree = {};
    nodes.forEach(n => {
        adjList[n.id] = [];
        inDegree[n.id] = 0;
    });
    
    connections.forEach(c => {
        if (adjList[c.from]) {
            adjList[c.from].push(c.to);
            if (inDegree[c.to] !== undefined) inDegree[c.to]++;
        }
    });

    const queue = [];
    Object.keys(inDegree).forEach(id => {
        if (inDegree[id] === 0) queue.push(id);
    });

    queue.sort((a, b) => nodes.find(n => n.id === a).x - nodes.find(n => n.id === b).x);

    const sortedNodeIds = [];
    while (queue.length > 0) {
        const curr = queue.shift();
        sortedNodeIds.push(curr);
        let neighbors = adjList[curr];
        neighbors.forEach(neighbor => {
            inDegree[neighbor]--;
            if (inDegree[neighbor] === 0) queue.push(neighbor);
        });
    }

    const sortedNodes = sortedNodeIds.map(id => nodes.find(n => n.id === id)).filter(n => n !== undefined);

    const varMap = {};
    sortedNodes.forEach((n, idx) => { 
        varMap[n.id] = `${n.toolId.split('_').pop()}_${idx+1}`; 
    });

    // --- DATA PROVENANCE ENGINE ---
    // Recursively traces a wire back to its root to determine what type of data it holds!
    const getProvenance = (nodeId) => {
        const node = nodes.find(n => n.id === nodeId);
        if (!node) return '';
        
        // Root Identifiers
        if (['wfs_sentinel2', 'wfs_elevation', 'load_raster'].includes(node.toolId)) return 'raster';
        if (['wfs_nlcd', 'wfs_census', 'load_vector', 'wfs_sciencebase'].includes(node.toolId)) return 'label';
        if (node.toolId === 'core_extent') return 'extent';
        
        // If it's a pass-through tool (like Pyramids or Buffer), trace its parents
        const parents = connections.filter(c => c.to === nodeId).map(c => c.from);
        for (let pid of parents) {
            const prov = getProvenance(pid);
            if (prov) return prov;
        }
        return '';
    };

    sortedNodes.forEach((n) => {
        let funcCall = "";
        
        const p = {};
        for (const [key, val] of Object.entries(n.params || {})) {
            p[key] = (val && typeof val === 'object' && val.type === 'select') ? val.value : val;
        }

        const outVar = varMap[n.id];
        const incomingCxs = connections.filter(c => c.to === n.id);
        const inNodes = incomingCxs.map(c => nodes.find(src => src.id === c.from));
        
        let inRasterVar = 'None';
        let inLabelVar = 'None';
        let inExtentVar = 'None';

        // Apply Provenance Tracing to assignments
        incomingCxs.forEach(c => {
            const prov = getProvenance(c.from);
            if (prov === 'raster') inRasterVar = varMap[c.from];
            else if (prov === 'label') inLabelVar = varMap[c.from];
            else if (prov === 'extent') inExtentVar = varMap[c.from];
        });

        const primaryInVar = inNodes.length > 0 ? varMap[inNodes[0].id] : 'None';

        // 1. Core Parameters
        if (n.toolId === 'core_extent') {
            funcCall = `${outVar} = arcpy.Extent(${p.xmin}, ${p.ymin}, ${p.xmax}, ${p.ymax})`;
        }
        else if (n.toolId === 'load_raster') {
            funcCall = `${outVar} = arcpy.Raster("${p.file_path}")`;
        }
        else if (n.toolId === 'load_vector') {
            funcCall = `${outVar} = "${p.file_path}"`;
        }
        // 3. WFS Sovereign Cloud
        else if (n.toolId === 'wfs_sentinel2') {
            const outFileName = `s2_cloud_extract_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.wfs.PullSentinel2(${inExtentVar}, "${outFileName}", max_cloud_cover=${p.max_cloud_cover}, date_range="${p.start_date}/${p.end_date}")`;
        }
        else if (n.toolId === 'wfs_elevation') {
            const outFileName = `usgs_dem_extract_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.wfs.PullUSGSElevation(${inExtentVar}, "${outFileName}")`;
        }
        else if (n.toolId === 'wfs_nlcd') {
            const outFileName = `nlcd_labels_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.wfs.PullNLCD(${inExtentVar}, "${outFileName}", year=${p.year}, product="${p.product}")`;
        }
        else if (n.toolId === 'wfs_sciencebase') {
            funcCall = `${outVar} = arcpy.wfs.PullScienceBase("${p.item_id}", "${p.out_folder}")`;
        }
        else if (n.toolId === 'wfs_census') {
            const outFileName = `census_tracts_${n.id.split('_')[1]}.shp`;
            funcCall = `${outVar} = arcpy.wfs.GetCensusTracts(${p.state_fips}, ${p.county_fips}, ${p.year}, "${outFileName}")`;
        }
        else if (n.toolId === 'wfs_universal') {
            const outFileName = `global_data_extract_${n.id.split('_')[1]}.shp`;
            funcCall = `${outVar} = arcpy.server.DownloadArcGISRESTFeatureLayer("${p.url}", "${outFileName}")`;
        }
        // 4. 3D Analyst
        else if (n.toolId === 'ddd_las_to_raster') {
            const outFileName = `lidar_dem_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.ddd.LasDatasetToRaster(${primaryInVar}, "${outFileName}", value_field="${p.value_field}", sampling_value=${p.sampling_value})`;
        }
        // 5. Image Analyst
        else if (n.toolId === 'ia_ndvi') {
            funcCall = `${outVar} = arcpy.ia.NDVI(${inRasterVar !== 'None' ? inRasterVar : primaryInVar}, nir_band_id=${p.nir_band}, red_band_id=${p.red_band})`;
        }
        else if (n.toolId === 'ia_pansharpen') {
            const outFileName = `pansharpened_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.ia.Pansharpen(in_raster=${primaryInVar}, panchromatic_image=${primaryInVar}, out_raster="${outFileName}", method="${p.method}")`;
        }
        else if (n.toolId === 'ia_export_dl') {
            funcCall = `${outVar} = arcpy.ia.ExportTrainingDataForDeepLearning(in_raster=getattr(${inRasterVar}, 'name', ${inRasterVar}), out_folder="${p.out_folder}", in_class_data=getattr(${inLabelVar}, 'name', ${inLabelVar}), tile_size_x=${p.tile_size}, tile_size_y=${p.tile_size}, stride_x=${p.stride}, stride_y=${p.stride}, shuffle_chips=${p.shuffle ? 'True' : 'False'})`;
        }
        // 6. GeoAI
        else if (n.toolId === 'ai_train') {
            const inFolderStr = primaryInVar !== 'None' ? `getattr(${primaryInVar}, 'output', ${primaryInVar})` : `"${p.in_folder}"`;
            funcCall = `${outVar} = arcpy.geoai.TrainDeepLearningModel(in_folder=${inFolderStr}, out_folder="${p.out_folder}", max_epochs=${p.max_epochs}, batch_size=${p.batch_size}, model_type="${p.model_type}")`;
        }
        else if (n.toolId === 'ai_detect') {
            funcCall = `${outVar} = arcpy.geoai.DetectObjectsUsingDeepLearning(getattr(${primaryInVar}, 'name', ${primaryInVar}), "${p.out_shp}", "${p.model}")`;
        }
        else if (n.toolId === 'ai_classify') {
            funcCall = `${outVar} = arcpy.geoai.ClassifyPixelsUsingDeepLearning(getattr(${primaryInVar}, 'name', ${primaryInVar}), "${p.out_raster}", "${p.model}")`;
        }
        // 7. Data Management
        else if (n.toolId === 'mgt_clip') {
            const outFileName = `aoi_clip_${n.id.split('_')[1]}.tif`;
            if (inExtentVar !== 'None') {
                funcCall = `${outVar} = arcpy.management.Clip(${inRasterVar}, ${inExtentVar}, "${outFileName}")`;
            } else {
                funcCall = `extent_poly = arcpy.Extent(${p.xmin}, ${p.ymin}, ${p.xmax}, ${p.ymax})\n${outVar} = arcpy.management.Clip(${inRasterVar}, extent_poly, "${outFileName}")`;
            }
        }
        else if (n.toolId === 'mgt_buffer') {
            funcCall = `${outVar} = arcpy.analysis.Buffer(${primaryInVar}, "out_buf.shp", "${p.distance} ${p.unit || ''}".strip())`;
        }
        else if (n.toolId === 'mgt_project_raster') {
            const outFileName = `proj_raster_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.management.ProjectRaster(${inRasterVar}, "${outFileName}", "${p.out_crs}", resampling_type="${p.resampling}")`;
        }
        else if (n.toolId === 'mgt_pyramids') {
            funcCall = `${outVar} = ${primaryInVar}\narcpy.management.BuildPyramidsAndStats(${primaryInVar}, build_pyramids=${p.build_pyramids ? 'True' : 'False'}, calculate_stats=${p.calculate_stats ? 'True' : 'False'})`;
        }
        else {
            funcCall = `# Execute ${n.name}`;
        }
        
        if(funcCall) script += `${funcCall}\n`;
    });
    
    if (processingScope === "Apache Airflow") {
        const indentedScript = script.split('\n').map(line => '        ' + line).join('\n');
        script = `from airflow.decorators import dag, task\nfrom datetime import datetime\n\n@dag(start_date=datetime(2026, 1, 1), schedule=None)\ndef magpi_pipeline():\n    @task\n    def run_magpi():\n${indentedScript}\n\n    run_magpi()\nmagpi_pipeline()`;
    }
    
    return script;
};