export const generatePythonScript = (nodes, connections, crs, processingScope) => {
    let script = `# Generated by MagPI Canvas\n`;
    script += `import magpi as arcpy\n`;
    script += `import os\n\n`;
    
    script += `# --- Global Environment ---\n`;
    script += `arcpy.env.workspace = "./tmp_wksp"\n`;
    
    const crsValue = crs.includes(':') ? crs.split(':')[1] : `"${crs}"`;
    script += `arcpy.env.outputCoordinateSystem = ${crsValue}\n`;
    script += `arcpy.env.overwriteOutput = True\n\n`;
    
    script += `arcpy.AddMessage("Initiating MagPI Visual Model execution...")\n\n`;
    
    // Sort nodes strictly by X coordinate (Left-to-Right execution)
    const sortedNodes = [...nodes].sort((a, b) => a.x - b.x);

    const varMap = {};
    sortedNodes.forEach((n, idx) => { 
        varMap[n.id] = `${n.toolId.split('_').pop()}_${idx+1}`; 
    });

    sortedNodes.forEach((n) => {
        let funcCall = "";
        
        const p = {};
        for (const [key, val] of Object.entries(n.params || {})) {
            p[key] = (val && typeof val === 'object' && val.type === 'select') ? val.value : val;
        }

        const outVar = varMap[n.id];
        
        // --- MULTI-WIRE INTELLIGENCE ---
        // Find ALL incoming connections to this node
        const incomingCxs = connections.filter(c => c.to === n.id);
        const inNodes = incomingCxs.map(c => nodes.find(src => src.id === c.from));

        // Helper function to find a specific type of incoming variable
        const getInVar = (typeMatches) => {
            const match = inNodes.find(src => typeMatches.some(t => src.toolId.includes(t)));
            return match ? varMap[match.id] : 'None';
        };

        // Categorize incoming wires! (FIXED: Separated Rasters from Labels)
        const inRasterVar = getInVar(['sentinel2', 'elevation', 'load_raster']) || 'None';
        const inLabelVar = getInVar(['nlcd', 'census', 'load_vector']) || 'None';
        const inExtentVar = getInVar(['extent']) || 'None';
        
        // Fallback for single-input tools
        const primaryInVar = inNodes.length > 0 ? varMap[inNodes[0].id] : 'None';

        // 1. Core Parameters
        if (n.toolId === 'core_extent') {
            funcCall = `${outVar} = arcpy.Extent(${p.xmin}, ${p.ymin}, ${p.xmax}, ${p.ymax})`;
        }
        
        // 2. Data Ingestion
        else if (n.toolId === 'load_raster') {
            funcCall = `${outVar} = arcpy.Raster("${p.file_path}")`;
        }
        else if (n.toolId === 'load_vector') {
            funcCall = `${outVar} = "${p.file_path}"`;
        }
        
        // 3. WFS Sovereign Cloud
        else if (n.toolId === 'wfs_sentinel2') {
            const outFileName = `s2_cloud_extract_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.wfs.PullSentinel2(${inExtentVar}, "${outFileName}", max_cloud_cover=${p.max_cloud_cover}, date_range="${p.start_date}/${p.end_date}")`;
        }
        else if (n.toolId === 'wfs_elevation') {
            const outFileName = `usgs_dem_extract_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.wfs.PullUSGSElevation(${inExtentVar}, "${outFileName}")`;
        }
        else if (n.toolId === 'wfs_nlcd') {
            const outFileName = `nlcd_labels_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.wfs.PullNLCD(${inExtentVar}, "${outFileName}", year=${p.year}, product="${p.product}")`;
        }
        else if (n.toolId === 'wfs_census') {
            const outFileName = `census_tracts_${n.id.split('_')[1]}.shp`;
            funcCall = `${outVar} = arcpy.wfs.GetCensusTracts(${p.state_fips}, ${p.county_fips}, ${p.year}, "${outFileName}")`;
        }
        else if (n.toolId === 'wfs_universal') {
            const outFileName = `global_data_extract_${n.id.split('_')[1]}.shp`;
            funcCall = `${outVar} = arcpy.server.DownloadArcGISRESTFeatureLayer("${p.url}", "${outFileName}")`;
        }

        // 4. 3D Analyst (LiDAR)
        else if (n.toolId === 'ddd_las_to_raster') {
            const outFileName = `lidar_dem_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.ddd.LasDatasetToRaster(${primaryInVar}, "${outFileName}", value_field="${p.value_field}", sampling_value=${p.sampling_value})`;
        }

        // 5. Image Analyst
        else if (n.toolId === 'ia_ndvi') {
            funcCall = `${outVar} = arcpy.ia.NDVI(${primaryInVar}, nir_band_id=${p.nir_band}, red_band_id=${p.red_band})`;
        }
        else if (n.toolId === 'ia_export_dl') {
            // FIXED: Now correctly assigns the Image and the Label independently!
            funcCall = `${outVar} = arcpy.ia.ExportTrainingDataForDeepLearning(in_raster=getattr(${inRasterVar}, 'name', ${inRasterVar}), out_folder="${p.out_folder}", in_class_data=getattr(${inLabelVar}, 'name', ${inLabelVar}), tile_size_x=${p.tile_size}, tile_size_y=${p.tile_size}, stride_x=${p.stride}, stride_y=${p.stride}, shuffle_chips=${p.shuffle ? 'True' : 'False'})`;
        }

        // 4. 3D Analyst (LiDAR)
        else if (n.toolId === 'ddd_las_to_raster') {
            const outFileName = `lidar_dem_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.ddd.LasDatasetToRaster(${primaryInVar}, "${outFileName}", value_field="${p.value_field}", sampling_value=${p.sampling_value})`;
        }

        // 6. GeoAI
        else if (n.toolId === 'ai_detect') {
            funcCall = `${outVar} = arcpy.geoai.DetectObjectsUsingDeepLearning(getattr(${primaryInVar}, 'name', ${primaryInVar}), "${p.out_shp}", "${p.model}")`;
        }
        else if (n.toolId === 'ai_classify') {
            funcCall = `${outVar} = arcpy.geoai.ClassifyPixelsUsingDeepLearning(getattr(${primaryInVar}, 'name', ${primaryInVar}), "${p.out_raster}", "${p.model}")`;
        }

        // 7. Data Management
        else if (n.toolId === 'mgt_clip') {
            const outFileName = `aoi_clip_${n.id.split('_')[1]}.tif`;
            if (inExtentVar !== 'None') {
                funcCall = `${outVar} = arcpy.management.Clip(${inRasterVar}, ${inExtentVar}, "${outFileName}")`;
            } else {
                funcCall = `extent_poly = arcpy.Extent(${p.xmin}, ${p.ymin}, ${p.xmax}, ${p.ymax})\n${outVar} = arcpy.management.Clip(${inRasterVar}, extent_poly, "${outFileName}")`;
            }
        }
        else if (n.toolId === 'mgt_project_raster') {
            const outFileName = `proj_raster_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.management.ProjectRaster(${inRasterVar}, "${outFileName}", "${p.out_crs}", resampling_type="${p.resampling}")`;
        }
        else if (n.toolId === 'mgt_buffer') {
            funcCall = `${outVar} = arcpy.analysis.Buffer(${primaryInVar}, "out_buf.shp", "${p.distance} ${p.unit || ''}".strip())`;
        }
        else if (n.toolId === 'mgt_pyramids') {
            funcCall = `arcpy.management.BuildPyramidsAndStats(${primaryInVar}, build_pyramids=${p.build_pyramids ? 'True' : 'False'}, calculate_stats=${p.calculate_stats ? 'True' : 'False'})`;
        }
        
        else {
            funcCall = `# Execute ${n.name}`;
        }
        
        if(funcCall) script += `${funcCall}\n`;
    });
    
    if (processingScope === "Apache Airflow") {
        const indentedScript = script.split('\n').map(line => '        ' + line).join('\n');
        script = `from airflow.decorators import dag, task\nfrom datetime import datetime\n\n@dag(start_date=datetime(2026, 1, 1), schedule=None)\ndef magpi_pipeline():\n    @task\n    def run_magpi():\n${indentedScript}\n\n    run_magpi()\nmagpi_pipeline()`;
    }
    
    return script;
};