export const generatePythonScript = (nodes, connections, crs, processingScope) => {
    let script = `# Generated by MagPI Canvas (v0.1.52 Alpha)\n`;
    script += `import magpi as arcpy\n`;
    script += `import os\n\n`;
    
    script += `# --- Global Environment ---\n`;
    script += `arcpy.env.workspace = "./tmp_wksp"\n`;
    
    const crsValue = crs.includes(':') ? crs.split(':')[1] : `"${crs}"`;
    script += `arcpy.env.outputCoordinateSystem = ${crsValue}\n`;
    script += `arcpy.env.overwriteOutput = True\n\n`;
    
    script += `arcpy.AddMessage("Initiating MagPI Visual Model execution...")\n\n`;
    
    const adjList = {};
    const inDegree = {};
    nodes.forEach(n => {
        adjList[n.id] = [];
        inDegree[n.id] = 0;
    });
    
    connections.forEach(c => {
        if (adjList[c.from]) {
            adjList[c.from].push(c.to);
            if (inDegree[c.to] !== undefined) inDegree[c.to]++;
        }
    });

    const queue = [];
    Object.keys(inDegree).forEach(id => {
        if (inDegree[id] === 0) queue.push(id);
    });

    queue.sort((a, b) => nodes.find(n => n.id === a).x - nodes.find(n => n.id === b).x);

    const sortedNodeIds = [];
    while (queue.length > 0) {
        const curr = queue.shift();
        sortedNodeIds.push(curr);
        let neighbors = adjList[curr];
        neighbors.forEach(neighbor => {
            inDegree[neighbor]--;
            if (inDegree[neighbor] === 0) queue.push(neighbor);
        });
    }

    const sortedNodes = sortedNodeIds.map(id => nodes.find(n => n.id === id)).filter(n => n !== undefined);

    const varMap = {};
    sortedNodes.forEach((n, idx) => { 
        varMap[n.id] = `${n.toolId.split('_').pop()}_${idx+1}`; 
    });

    const getProvenance = (nodeId) => {
        const node = nodes.find(n => n.id === nodeId);
        if (!node) return '';
        
        if (['wfs_sentinel2', 'wfs_elevation', 'load_raster'].includes(node.toolId)) return 'raster';
        if (['wfs_nlcd', 'wfs_census', 'load_vector', 'wfs_sciencebase', 'ia_reclassify', 'ai_classify'].includes(node.toolId)) return 'label';
        if (node.toolId === 'core_extent') return 'extent';
        
        const parents = connections.filter(c => c.to === nodeId).map(c => c.from);
        for (let pid of parents) {
            const prov = getProvenance(pid);
            if (prov) return prov;
        }
        return '';
    };

    sortedNodes.forEach((n) => {
        let funcCall = "";
        
        const p = {};
        for (const [key, val] of Object.entries(n.params || {})) {
            p[key] = (val && typeof val === 'object' && val.type === 'select') ? val.value : val;
        }

        const outVar = varMap[n.id];
        const incomingCxs = connections.filter(c => c.to === n.id);
        const inNodes = incomingCxs.map(c => nodes.find(src => src.id === c.from));
        
        let inRasterVar = 'None';
        let inLabelVar = 'None';
        let inExtentVar = 'None';

        incomingCxs.forEach(c => {
            const { from } = c;
            const prov = getProvenance(from);
            if (prov === 'raster') inRasterVar = varMap[from];
            else if (prov === 'label') inLabelVar = varMap[from];
            else if (prov === 'extent') inExtentVar = varMap[from];
        });

        const primaryInVar = inNodes.length > 0 ? varMap[inNodes[0].id] : 'None';

        if (n.toolId === 'core_extent') {
            funcCall = `${outVar} = arcpy.Extent(${p.xmin}, ${p.ymin}, ${p.xmax}, ${p.ymax})`;
        }
        else if (n.toolId === 'load_raster') {
            funcCall = `${outVar} = arcpy.Raster("${p.file_path}")`;
        }
        else if (n.toolId === 'load_vector') {
            funcCall = `${outVar} = "${p.file_path}"`;
        }
        else if (n.toolId === 'wfs_sentinel2') {
            const outFileName = `s2_cloud_extract_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.wfs.PullSentinel2(${inExtentVar}, "${outFileName}", max_cloud_cover=${p.max_cloud_cover}, date_range="${p.start_date}/${p.end_date}")`;
        }
        else if (n.toolId === 'wfs_elevation') {
            const outFileName = `usgs_dem_extract_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.wfs.PullUSGSElevation(${inExtentVar}, "${outFileName}")`;
        }
        else if (n.toolId === 'wfs_nlcd') {
            const outFileName = `nlcd_labels_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.wfs.PullNLCD(${inExtentVar}, "${outFileName}", year=${p.year}, product="${p.product}")`;
        }
        else if (n.toolId === 'wfs_sciencebase') {
            funcCall = `${outVar} = arcpy.wfs.PullScienceBase("${p.item_id}", "${p.out_folder}")`;
        }
        else if (n.toolId === 'wfs_census') {
            const outFileName = `census_tracts_${n.id.split('_')[1]}.shp`;
            funcCall = `${outVar} = arcpy.wfs.GetCensusTracts(${p.state_fips}, ${p.county_fips}, ${p.year}, "${outFileName}")`;
        }
        else if (n.toolId === 'wfs_universal') {
            const outFileName = `global_data_extract_${n.id.split('_')[1]}.shp`;
            funcCall = `${outVar} = arcpy.server.DownloadArcGISRESTFeatureLayer("${p.url}", "${outFileName}")`;
        }
        else if (n.toolId === 'ddd_las_to_raster') {
            const outFileName = `lidar_dem_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.ddd.LasDatasetToRaster(${primaryInVar}, "${outFileName}", value_field="${p.value_field}", sampling_value=${p.sampling_value})`;
        }
        else if (n.toolId === 'ia_ndvi') {
            funcCall = `${outVar} = arcpy.ia.NDVI(${inRasterVar !== 'None' ? inRasterVar : primaryInVar}, nir_band_id=${p.nir_band}, red_band_id=${p.red_band})`;
        }
        else if (n.toolId === 'ia_pansharpen') {
            const outFileName = `pansharpened_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.ia.Pansharpen(in_raster=${primaryInVar}, panchromatic_image=${primaryInVar}, out_raster="${outFileName}", method="${p.method}")`;
        }
        else if (n.toolId === 'ia_reclassify') {
            const outFileName = `reclassified_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.ia.Reclassify(in_raster=${primaryInVar}, out_raster="${outFileName}", remap_string="${p.remap_string}")`;
        }
        else if (n.toolId === 'ia_export_dl') {
            funcCall = `${outVar} = arcpy.ia.ExportTrainingDataForDeepLearning(in_raster=getattr(${inRasterVar}, 'name', ${inRasterVar}), out_folder="${p.out_folder}", in_class_data=getattr(${inLabelVar}, 'name', ${inLabelVar}), tile_size_x=${p.tile_size}, tile_size_y=${p.tile_size}, stride_x=${p.stride}, stride_y=${p.stride}, shuffle_chips=${p.shuffle ? 'True' : 'False'})`;
        }
        else if (n.toolId === 'ai_train') {
            const inFolderStr = primaryInVar !== 'None' ? `getattr(${primaryInVar}, 'output', ${primaryInVar})` : `"${p.in_folder}"`;
            funcCall = `${outVar} = arcpy.geoai.TrainDeepLearningModel(in_folder=${inFolderStr}, out_folder="${p.out_folder}", max_epochs=${p.max_epochs}, batch_size=${p.batch_size}, model_type="${p.model_type}")`;
        }
        else if (n.toolId === 'ai_detect') {
            funcCall = `${outVar} = arcpy.geoai.DetectObjectsUsingDeepLearning(getattr(${primaryInVar}, 'name', ${primaryInVar}), "${p.out_shp}", "${p.model}")`;
        }
        else if (n.toolId === 'ai_classify') {
            funcCall = `${outVar} = arcpy.geoai.ClassifyPixelsUsingDeepLearning(getattr(${primaryInVar}, 'name', ${primaryInVar}), "${p.out_raster}", "${p.model}")`;
        }
        else if (n.toolId === 'mgt_clip') {
            const outFileName = `aoi_clip_${n.id.split('_')[1]}.tif`;
            if (inExtentVar !== 'None') {
                funcCall = `${outVar} = arcpy.management.Clip(${inRasterVar}, ${inExtentVar}, "${outFileName}")`;
            } else {
                funcCall = `extent_poly = arcpy.Extent(${p.xmin}, ${p.ymin}, ${p.xmax}, ${p.ymax})\n${outVar} = arcpy.management.Clip(${inRasterVar}, extent_poly, "${outFileName}")`;
            }
        }
        else if (n.toolId === 'mgt_buffer') {
            funcCall = `${outVar} = arcpy.analysis.Buffer(${primaryInVar}, "out_buf.shp", "${p.distance} ${p.unit || ''}".strip())`;
        }
        else if (n.toolId === 'mgt_project_raster') {
            const outFileName = `proj_raster_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.management.ProjectRaster(${inRasterVar}, "${outFileName}", "${p.out_crs}", resampling_type="${p.resampling}")`;
        }
        else if (n.toolId === 'mgt_pyramids') {
            funcCall = `${outVar} = ${primaryInVar}\narcpy.management.BuildPyramidsAndStats(${primaryInVar}, build_pyramids=${p.build_pyramids ? 'True' : 'False'}, calculate_stats=${p.calculate_stats ? 'True' : 'False'})`;
        }
        else if (n.toolId === 'conv_raster_to_polygon') {
            funcCall = `${outVar} = arcpy.conversion.RasterToPolygon(in_raster=${primaryInVar}, out_polygon_features="${p.out_polygon_features}", background_value=${p.background_value})`;
        }
        // FIXED: Multi-input resolution logic for the Confusion Matrix
        else if (n.toolId === 'stats_confusion_matrix') {
            let refVar = 'None';
            let predVar = 'None';
            
            incomingCxs.forEach(c => {
                const srcNode = nodes.find(src => src.id === c.from);
                if (!srcNode) return;
                
                // Explicitly check for classified/prediction tools vs ground-truth references
                const isPrediction = ['ai_classify', 'ai_detect'].includes(srcNode.toolId);
                const isReference = ['ia_reclassify', 'wfs_nlcd', 'load_vector'].includes(srcNode.toolId);
                
                if (isPrediction) {
                    predVar = varMap[c.from];
                } else if (isReference) {
                    refVar = varMap[c.from];
                } else {
                    const prov = getProvenance(c.from);
                    if (prov === 'label') refVar = varMap[c.from];
                    else predVar = varMap[c.from];
                }
            });
            
            if (refVar === 'None' && inNodes.length > 0) refVar = varMap[inNodes[0].id];
            if (predVar === 'None' && inNodes.length > 1) predVar = varMap[inNodes[1].id];
            
            funcCall = `${outVar} = arcpy.stats.ComputeConfusionMatrix(in_ground_truth=${refVar}, in_classified=${predVar}, out_table="${p.out_table}")`;
        }
        else if (n.toolId === 'etl_spatial_join') {
            let targetVar = 'None', joinVar = 'None';
            incomingCxs.forEach(c => {
                if (c.targetHandle === 'in1') targetVar = varMap[c.from];
                else if (c.targetHandle === 'in2') joinVar = varMap[c.from];
            });
            if (targetVar === 'None' && inNodes.length > 0) targetVar = varMap[inNodes[0].id];
            if (joinVar === 'None' && inNodes.length > 1) joinVar = varMap[inNodes[1].id];
            
            const outFileName = `spatial_join_${n.id.split('_')[1]}.shp`;
            funcCall = `${outVar} = arcpy.analysis.SpatialJoin(target_features=${targetVar}, join_features=${joinVar}, out_feature_class="${outFileName}", join_operation="${p.join_operation}")`;
        }
        else if (n.toolId === 'etl_field_calc') {
            funcCall = `${outVar} = arcpy.management.CalculateField(in_table=${primaryInVar}, field="${p.field_name}", expression="${p.expression}")`;
        }
        else if (n.toolId === 'etl_db_writer') {
            funcCall = `arcpy.conversion.ExportToPostGIS(in_features=${primaryInVar}, connection_string="${p.connection_string}", table_name="${p.table_name}")`;
        }
        else if (n.toolId === 'envi_band_math') {
            const outFileName = `band_math_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.sa.RasterCalculator(expression="${p.expression}", in_raster=${primaryInVar})\n${outVar}.save("${outFileName}")`;
        }
        else if (n.toolId === 'envi_pca') {
            const outFileName = `pca_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.sa.PrincipalComponents(in_raster_bands=${primaryInVar})\n${outVar}.save("${outFileName}")`;
        }
        else if (n.toolId === 'envi_tasseled_cap') {
            const outFileName = `tasseled_cap_${n.id.split('_')[1]}.tif`;
            funcCall = `${outVar} = arcpy.sa.TasseledCap(in_raster=${primaryInVar}, sensor="${p.sensor}")\n${outVar}.save("${outFileName}")`;
        }
        else {
            funcCall = `# Execute ${n.name}`;
        }
        
        if(funcCall) script += `${funcCall}\n`;
    });
    
    if (processingScope === "Apache Airflow") {
        const indentedScript = script.split('\n').map(line => '        ' + line).join('\n');
        script = `from airflow.decorators import dag, task\nfrom datetime import datetime\n\n@dag(start_date=datetime(2026, 1, 1), schedule=None)\ndef magpi_pipeline():\n    @task\n    def run_magpi():\n${indentedScript}\n\n    run_magpi()\nmagpi_pipeline()`;
    }
    
    return script;
};