# Generated by MagPI Canvas (v0.1.52 Alpha)
import magpi as arcpy
import openeo
import os

# --- Global Environment ---
arcpy.env.workspace = "./magpi_workspace"
arcpy.env.scratchWorkspace = "./magpi_scratch"
arcpy.env.outputWorkspace = "./magpi_output"
arcpy.env.outputCoordinateSystem = 6438
arcpy.env.overwriteOutput = True

arcpy.AddMessage("Initiating MagPI Visual Model execution...")

extent_1 = arcpy.Extent(-81.55384, 27.75887, -81.41668, 27.85850)
extent_2 = arcpy.Extent(-81.46558, 27.68089, -81.32908, 27.77892)
extent_3 = arcpy.Extent(-81.40267, 27.77089, -81.28471, 27.88022)
sentinel2_4 = []
for i, ext in enumerate([extent_2, extent_1, extent_3]):
    sentinel2_4.append(arcpy.wfs.PullSentinel2(ext, f"s2_cloud_extract_1779539443595_{i}.tif", max_cloud_cover=10, date_range="2023-01-01/2023-12-31"))
sentinel2_5 = []
for i, ext in enumerate([extent_3, extent_1, extent_2]):
    sentinel2_5.append(arcpy.wfs.PullSentinel2(ext, f"s2_cloud_extract_1779539452156_{i}.tif", max_cloud_cover=10, date_range="2024-01-01/2024-12-31"))
pyramids_6 = sentinel2_4
arcpy.management.BuildPyramidsAndStats(sentinel2_4, build_pyramids=False, calculate_stats=True)
pyramids_7 = sentinel2_5
arcpy.management.BuildPyramidsAndStats(sentinel2_5, build_pyramids=False, calculate_stats=True)
ndvi_8 = [arcpy.ia.NDVI(r, nir_band_id=4, red_band_id=3) for r in pyramids_6] if isinstance(pyramids_6, list) else arcpy.ia.NDVI(pyramids_6, nir_band_id=4, red_band_id=3)
ndvi_9 = [arcpy.ia.NDVI(r, nir_band_id=4, red_band_id=3) for r in pyramids_7] if isinstance(pyramids_7, list) else arcpy.ia.NDVI(pyramids_7, nir_band_id=4, red_band_id=3)
pyramids_10 = ndvi_8
arcpy.management.BuildPyramidsAndStats(ndvi_8, build_pyramids=False, calculate_stats=True)
pyramids_11 = ndvi_9
arcpy.management.BuildPyramidsAndStats(ndvi_9, build_pyramids=False, calculate_stats=True)
_expr = "A - B"
math_12 = [arcpy.ia.RasterMath(a, b, _expr, f"raster_math_{i}.tif") for i, (a, b) in enumerate(zip(pyramids_11 if isinstance(pyramids_11, list) else [pyramids_11], pyramids_10 if isinstance(pyramids_10, list) else [pyramids_10]))]
