# Generated by MagPI Canvas (v0.1.52 Alpha)
import magpi as arcpy
import openeo
import os

# --- Global Environment ---
arcpy.env.workspace = "./magpi_workspace"
arcpy.env.scratchWorkspace = "./magpi_scratch"
arcpy.env.outputWorkspace = "./magpi_output"
arcpy.env.outputCoordinateSystem = 6438
arcpy.env.overwriteOutput = True

arcpy.AddMessage("Initiating MagPI Visual Model execution...")

extent_1 = arcpy.Extent(-81.56415, 28.56250, -81.54906, 28.57336)
extent_2 = arcpy.Extent(-81.56822, 28.55082, -81.54414, 28.56778)
extent_3 = arcpy.Extent(-81.57533, 28.53882, -81.53006, 28.55693)
sentinel2_4 = []
for i, ext in enumerate([extent_2, extent_1, extent_3]):
    sentinel2_4.append(arcpy.wfs.PullSentinel2(ext, f"s2_cloud_extract_1779536341550_{i}.tif", max_cloud_cover=10, date_range="2023-01-01/2023-12-31"))
sentinel2_5 = []
for i, ext in enumerate([extent_2, extent_1, extent_3]):
    sentinel2_5.append(arcpy.wfs.PullSentinel2(ext, f"s2_cloud_extract_1779538166439_{i}.tif", max_cloud_cover=10, date_range="2023-01-01/2023-12-31"))
pyramids_6 = sentinel2_4
arcpy.management.BuildPyramidsAndStats(sentinel2_4, build_pyramids=False, calculate_stats=True)
index_7 = sentinel2_4[3] if isinstance(sentinel2_4, list) and len(sentinel2_4) > 3 else sentinel2_4
pyramids_8 = sentinel2_5
arcpy.management.BuildPyramidsAndStats(sentinel2_5, build_pyramids=False, calculate_stats=True)
ndvi_9 = [arcpy.ia.NDVI(r, nir_band_id=4, red_band_id=3) for r in pyramids_6] if isinstance(pyramids_6, list) else arcpy.ia.NDVI(pyramids_6, nir_band_id=4, red_band_id=3)
pyramids_10 = index_7
arcpy.management.BuildPyramidsAndStats(index_7, build_pyramids=False, calculate_stats=True)
ndvi_11 = [arcpy.ia.NDVI(r, nir_band_id=4, red_band_id=3) for r in pyramids_8] if isinstance(pyramids_8, list) else arcpy.ia.NDVI(pyramids_8, nir_band_id=4, red_band_id=3)
_expr = "A - B"
math_12 = [arcpy.ia.RasterMath(a, b, _expr, f"raster_math_{i}.tif") for i, (a, b) in enumerate(zip(ndvi_9 if isinstance(ndvi_9, list) else [ndvi_9], ndvi_11 if isinstance(ndvi_11, list) else [ndvi_11]))]
pyramids_13 = math_12
arcpy.management.BuildPyramidsAndStats(math_12, build_pyramids=False, calculate_stats=True)
