# Generated by MagPI Canvas (v0.1.52 Alpha) - Hydro Detection Test Pipeline
import magpi as arcpy
import os

# --- Global Environment ---
arcpy.env.workspace = "./magpi_workspace"
arcpy.env.scratchWorkspace = "./magpi_scratch"
arcpy.env.outputWorkspace = "./magpi_output"
arcpy.env.outputCoordinateSystem = 6438
arcpy.env.overwriteOutput = True

arcpy.AddMessage("Initiating MagPI Visual Model execution: Hydro-Detection")

# Node 1: Spatial Extent (Very Small 1x1 km)
extent_1 = arcpy.Extent(-81.4, 27.8, -81.39, 27.81)

# Node 2: STAC Pull Sentinel-2 (T1: 2023)
sentinel_t1 = arcpy.wfs.PullSentinel2(
    extent_1, 
    "s2_hydro_t1_2023.tif", 
    max_cloud_cover=10, 
    date_range="2023-01-01/2023-12-31", 
    item_ids="S2B_17RML_20231119_0_L2A", 
    bands="B02,B03,B04,B08"
)

# Node 3: STAC Pull Sentinel-2 (T2: 2024)
sentinel_t2 = arcpy.wfs.PullSentinel2(
    extent_1, 
    "s2_hydro_t2_2024.tif", 
    max_cloud_cover=10, 
    date_range="2024-01-01/2024-12-31", 
    item_ids="S2B_17RML_20241123_0_L2A", 
    bands="B02,B03,B04,B08"
)

# Node 4: Raster Math (NDWI T1) -> Formula: (B03 - B08) / (B03 + B08)
# In our array, B03 is band 2 (b2), and B08 is band 4 (b4)
_expr_ndwi = "(b2 - b4) / (b2 + b4)"
ndwi_t1 = arcpy.ia.RasterMath(sentinel_t1, None, _expr_ndwi, "ndwi_t1_2023.tif")

# Node 5: Raster Math (NDWI T2)
ndwi_t2 = arcpy.ia.RasterMath(sentinel_t2, None, _expr_ndwi, "ndwi_t2_2024.tif")

# Node 6: Raster Math (Change Detection: T2 - T1) -> Formula: B - A
_expr_change = "B - A"
ndwi_change = arcpy.ia.RasterMath(ndwi_t1, ndwi_t2, _expr_change, "ndwi_change_final.tif")

if ndwi_change.status == 0:
    arcpy.AddMessage(f"SUCCESS: Pipeline complete. Output: {ndwi_change.output}")
else:
    arcpy.AddMessage("ERROR: Pipeline failed.")
