# Generated by MagPI Canvas (v0.1.52 Alpha)
import magpi as arcpy
import openeo
import os

# --- Global Environment ---
arcpy.env.workspace = "./magpi_workspace"
arcpy.env.scratchWorkspace = "./magpi_scratch"
arcpy.env.outputWorkspace = "./magpi_output"
arcpy.env.outputCoordinateSystem = 6438
arcpy.env.overwriteOutput = True

arcpy.AddMessage("Initiating MagPI Visual Model execution...")

extent_1 = arcpy.Extent(-81.55384, 27.75887, -81.41668, 27.85850)
extent_2 = arcpy.Extent(-81.46558, 27.68089, -81.32908, 27.77892)
extent_3 = arcpy.Extent(-81.40267, 27.77089, -81.28471, 27.88022)
sentinel2_4 = []
for i, ext in enumerate([extent_2, extent_1, extent_3]):
    sentinel2_4.append(arcpy.wfs.PullSentinel2(ext, f"s2_cloud_extract_1779552489338_{i}.tif", max_cloud_cover=10, date_range="2023-01-01/2023-12-31", item_ids="S2B_57MYN_20231231_0_L2A", bands="B02,B03,B04,B08"))
sentinel2_5 = []
for i, ext in enumerate([extent_3, extent_1, extent_2]):
    sentinel2_5.append(arcpy.wfs.PullSentinel2(ext, f"s2_cloud_extract_1779553078691_{i}.tif", max_cloud_cover=10, date_range="2024-01-01/2024-12-31", item_ids="S2A_49CDN_20241231_2_L2A", bands="B02,B03,B04,B08"))
ndvi_6 = [arcpy.ia.NDVI(r, nir_band_id=4, red_band_id=3) for r in sentinel2_4] if isinstance(sentinel2_4, list) else arcpy.ia.NDVI(sentinel2_4, nir_band_id=4, red_band_id=3)
ndvi_7 = [arcpy.ia.NDVI(r, nir_band_id=4, red_band_id=3) for r in sentinel2_5] if isinstance(sentinel2_5, list) else arcpy.ia.NDVI(sentinel2_5, nir_band_id=4, red_band_id=3)
_expr = "A - B"
math_8 = [arcpy.ia.RasterMath(a, b, _expr, f"raster_math_{i}.tif") for i, (a, b) in enumerate(zip(ndvi_6 if isinstance(ndvi_6, list) else [ndvi_6], ndvi_7 if isinstance(ndvi_7, list) else [ndvi_7]))]
